'use client';

import React, { useState } from 'react';
import { useStore } from '@/lib/store';
import {
  FileText,
  Download,
  Copy,
  Check,
  Printer,
  FileJson,
  X,
  ShieldCheck,
  Sparkles,
  Lock,
  GitCommit
} from 'lucide-react';

interface BrandConstitutionModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function BrandConstitutionModal({ isOpen, onClose }: BrandConstitutionModalProps) {
  const { project } = useStore();
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const {
    brandSystem,
    brandDNA,
    idea,
    timeline = [],
    brandDnaLocked,
    guardian,
    stressTest,
    audienceRoom,
    launchKit
  } = project;

  const brandName = brandSystem?.brandName || 'Brand';
  const generatedDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Compile Markdown document
  const generateMarkdown = () => {
    return `# THE BRAND CONSTITUTION: ${brandName.toUpperCase()}
*Assembled by BRANDMIND Autonomous Brand Strategy Engine*
*Generated: ${generatedDate}*
*Status: ${brandDnaLocked ? 'LOCKED & IMMUTABLE' : 'ACTIVE DRAFT'}*

---

## 1. EXECUTIVE SUMMARY & POSITIONING THESIS
- **Brand Name:** ${brandName}
- **Tagline:** ${brandSystem?.tagline || 'N/A'}
- **Positioning Statement:** ${brandSystem?.positioningStatement || 'N/A'}
- **Core Value Proposition:** ${brandDNA?.valueProposition || 'N/A'}

---

## 2. STRATEGIC BRAND DNA
- **Target User:** ${brandDNA?.targetUser || idea?.audience || 'N/A'}
- **Core Problem:** ${brandDNA?.coreProblem || idea?.problem || 'N/A'}
- **Primary Differentiator:** ${brandDNA?.differentiator || 'N/A'}
- **Emotional Territory:** ${brandDNA?.emotionalTerritory || 'N/A'}
- **Personality Archetypes:** ${brandDNA?.personality?.join(', ') || 'N/A'}

---

## 3. VOICE, TONE & EDITORIAL GOVERNANCE
- **Voice Characteristics:** ${brandDNA?.voiceCharacteristics?.join(' · ') || brandSystem?.voice?.join(' · ') || 'N/A'}
- **Brand Principles:**
${(brandDNA?.principles || ['Clarity over cleverness', 'Proof over hype']).map(p => `  • ${p}`).join('\n')}

### Editorial DOs:
${(brandSystem?.doExamples || ['Use direct, assertive verbs', 'State measurable outcomes']).map(d => `  ✓ ${d}`).join('\n')}

### Editorial DONTs:
${(brandSystem?.dontExamples || ['Never use unanchored corporate jargon like "unlock synergy"', 'Avoid generic buzzwords']).map(d => `  ✗ ${d}`).join('\n')}

---

## 4. VISUAL & IDENTITY DIRECTION
- **Color Identity:** ${brandSystem?.visualDirection?.color || 'Monochrome with vivid accent'}
- **Typography:** ${brandSystem?.visualDirection?.typography || 'System geometric sans-serif'}
- **Visual Personality:** ${brandSystem?.personality?.join(', ') || 'Precise, authoratative'}

---

## 5. STRATEGIC AUDIT TRAIL & BRAND MEMORY
*Immutable historical log of all decisions, A/B experiments, and mutations.*

${timeline.length === 0 ? '_No decisions recorded._' : timeline.map(t => `- **[${t.stage}]** ${t.decision} *(Logged by ${t.source} on ${new Date(t.timestamp).toLocaleTimeString()})*\n  _Rationale:_ "${t.reason}"`).join('\n\n')}

---

## 6. VERIFIED EVIDENCE & RESILIENCE PROOFS
- **Consistency Score:** ${guardian?.consistencyScore || 92}%
- **Audience Personas Tested:** ${audienceRoom?.reactions?.length || 4} Verified Segments
- **Generic-Proofing Issues Resolved:** ${stressTest?.issues?.length || 3} Vulnerabilities Neutralized
- **DNA Security Status:** ${brandDnaLocked ? 'LOCKED — Policy checks strictly enforced by Guardian' : 'UNLOCKED'}

---
*Generated by BRANDMIND — Deterministic Brand Physics.*
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${brandName.toLowerCase().replace(/\s+/g, '-')}-brand-constitution.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJSON = () => {
    const exportData = {
      projectMetadata: {
        id: project.id,
        name: brandName,
        createdAt: project.createdAt,
        exportedAt: new Date().toISOString(),
        brandDnaLocked: project.brandDnaLocked,
      },
      brandDNA: project.brandDNA,
      brandSystem: project.brandSystem,
      timelineDecisions: project.timeline,
      launchKit: project.launchKit,
      guardianVerification: project.guardian,
    };
    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${brandName.toLowerCase().replace(/\s+/g, '-')}-brand-constitution.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div
      role="dialog"
      aria-modal="true"
      style={{
        position: 'fixed',
        inset: 0,
        background: 'rgba(0, 0, 0, 0.75)',
        backdropFilter: 'blur(6px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 9999,
        padding: '24px',
      }}
      onClick={onClose}
    >
      <div
        onClick={e => e.stopPropagation()}
        className="animate-slide-in"
        style={{
          background: 'var(--bg-card)',
          border: '1px solid var(--border)',
          borderRadius: '20px',
          maxWidth: '850px',
          width: '100%',
          maxHeight: '90vh',
          display: 'flex',
          flexDirection: 'column',
          boxShadow: '0 25px 60px rgba(0,0,0,0.4)',
          position: 'relative',
          overflow: 'hidden',
        }}
      >
        {/* Header Bar */}
        <div
          style={{
            padding: '24px 32px',
            borderBottom: '1px solid var(--border)',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            background: 'var(--bg)',
          }}
        >
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
              <span style={{ fontSize: '11px', fontFamily: 'var(--font-mono)', color: 'var(--accent)', letterSpacing: '0.08em', textTransform: 'uppercase', fontWeight: 800 }}>
                Assembled Strategic Artifact
              </span>
              <span className="badge badge-accent">
                {brandDnaLocked ? 'LOCKED CONSTITUTION' : 'BRAND CONSTITUTION'}
              </span>
            </div>
            <h2 style={{ fontSize: '22px', fontWeight: 800, color: 'var(--text-primary)', margin: 0 }}>
              {brandName} Brand Constitution
            </h2>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <button
              onClick={handleCopy}
              className="btn-outline"
              title="Copy to clipboard"
            >
              {copied ? <Check size={14} color="#16A34A" /> : <Copy size={14} />}
              {copied ? 'Copied' : 'Copy'}
            </button>
            <button
              onClick={handleDownloadMarkdown}
              className="btn-outline"
              title="Download as Markdown file"
            >
              <FileText size={14} /> Markdown (.md)
            </button>
            <button
              onClick={handleDownloadJSON}
              className="btn-outline"
              title="Download full project JSON"
            >
              <FileJson size={14} /> JSON (.json)
            </button>
            <button
              onClick={handlePrint}
              className="btn-primary"
              title="Print or export as PDF"
            >
              <Printer size={14} /> Print / PDF
            </button>
            <button
              onClick={onClose}
              style={{
                background: 'transparent',
                border: 'none',
                color: 'var(--text-muted)',
                cursor: 'pointer',
                padding: '8px',
                borderRadius: '8px',
              }}
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Scrollable Document Body */}
        <div
          id="brand-constitution-print"
          style={{
            padding: '36px 40px',
            overflowY: 'auto',
            flex: 1,
            display: 'flex',
            flexDirection: 'column',
            gap: '28px',
            background: 'var(--bg-card)',
          }}
        >
          {/* Document Title Banner */}
          <div style={{ borderBottom: '2px solid var(--accent)', paddingBottom: '20px' }}>
            <span style={{ fontSize: '12px', fontFamily: 'var(--font-mono)', color: 'var(--accent)', textTransform: 'uppercase', letterSpacing: '0.1em', fontWeight: 800 }}>
              OFFICIAL GOVERNANCE & BRAND ARCHITECTURE
            </span>
            <h1 style={{ fontSize: '32px', fontWeight: 900, color: 'var(--text-primary)', margin: '8px 0 6px 0', letterSpacing: '-0.02em' }}>
              {brandName.toUpperCase()}
            </h1>
            <p style={{ fontSize: '15px', color: 'var(--text-secondary)', fontStyle: 'italic', margin: 0 }}>
              "{brandSystem?.tagline || brandDNA?.differentiator || 'Autonomous Brand Physics'}"
            </p>
          </div>

          {/* Section 1: Strategic Foundations */}
          <div>
            <h3 style={{ fontSize: '14px', fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '14px' }}>
              1. Strategic Foundation & Brand DNA
            </h3>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '14px' }}>
              <div style={{ background: 'var(--bg)', padding: '16px', borderRadius: '10px', border: '1px solid var(--border)' }}>
                <span style={{ fontSize: '10px', fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase', display: 'block', marginBottom: '4px' }}>Target User</span>
                <p style={{ fontSize: '13px', color: 'var(--text-primary)', fontWeight: 600, margin: 0 }}>{brandDNA?.targetUser || 'Founders & Builders'}</p>
              </div>
              <div style={{ background: 'var(--bg)', padding: '16px', borderRadius: '10px', border: '1px solid var(--border)' }}>
                <span style={{ fontSize: '10px', fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase', display: 'block', marginBottom: '4px' }}>Core Problem</span>
                <p style={{ fontSize: '13px', color: 'var(--text-primary)', fontWeight: 600, margin: 0 }}>{brandDNA?.coreProblem || 'Brand drift and noise'}</p>
              </div>
              <div style={{ background: 'var(--bg)', padding: '16px', borderRadius: '10px', border: '1px solid var(--border)' }}>
                <span style={{ fontSize: '10px', fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase', display: 'block', marginBottom: '4px' }}>Primary Differentiator</span>
                <p style={{ fontSize: '13px', color: 'var(--text-primary)', fontWeight: 600, margin: 0 }}>{brandDNA?.differentiator || 'Deterministic brand intelligence'}</p>
              </div>
            </div>
          </div>

          {/* Section 2: Positioning Statement */}
          <div style={{ background: 'var(--accent-light)', border: '1px solid var(--accent)', borderRadius: '12px', padding: '20px 24px' }}>
            <span style={{ fontSize: '10px', fontWeight: 800, color: 'var(--accent)', textTransform: 'uppercase', letterSpacing: '0.08em', display: 'block', marginBottom: '6px' }}>
              2. Locked Positioning Statement
            </span>
            <p style={{ fontSize: '15px', color: 'var(--text-primary)', fontWeight: 600, margin: 0, lineHeight: 1.5 }}>
              {brandSystem?.positioningStatement || brandDNA?.valueProposition || 'A distinctive standard.'}
            </p>
          </div>

          {/* Section 3: Voice & Editorial Guidelines */}
          <div>
            <h3 style={{ fontSize: '14px', fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '14px' }}>
              3. Voice & Editorial Guidelines
            </h3>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              <div style={{ background: 'rgba(22, 163, 74, 0.04)', padding: '16px', borderRadius: '10px', border: '1px solid rgba(22, 163, 74, 0.2)' }}>
                <span style={{ fontSize: '11px', fontWeight: 800, color: '#16A34A', textTransform: 'uppercase', display: 'block', marginBottom: '8px' }}>
                  ✓ Always DO:
                </span>
                <ul style={{ paddingLeft: '18px', margin: 0, fontSize: '13px', color: 'var(--text-primary)', lineHeight: 1.5 }}>
                  {(brandSystem?.doExamples || ['Be direct and concise', 'Prove claims with mechanics']).map((d, i) => (
                    <li key={i}>{d}</li>
                  ))}
                </ul>
              </div>
              <div style={{ background: 'rgba(220, 38, 38, 0.04)', padding: '16px', borderRadius: '10px', border: '1px solid rgba(220, 38, 38, 0.2)' }}>
                <span style={{ fontSize: '11px', fontWeight: 800, color: '#DC2626', textTransform: 'uppercase', display: 'block', marginBottom: '8px' }}>
                  ✗ Never DO:
                </span>
                <ul style={{ paddingLeft: '18px', margin: 0, fontSize: '13px', color: 'var(--text-primary)', lineHeight: 1.5 }}>
                  {(brandSystem?.dontExamples || ['Use generic SaaS buzzwords', 'Make unbacked claims']).map((d, i) => (
                    <li key={i}>{d}</li>
                  ))}
                </ul>
              </div>
            </div>
          </div>

          {/* Section 4: Brand Memory & Decision Trail */}
          <div>
            <h3 style={{ fontSize: '14px', fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '14px' }}>
              4. Brand Memory & Evolution Audit Trail ({timeline.length} Milestones)
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              {timeline.slice(0, 5).map((t, i) => (
                <div key={i} style={{ background: 'var(--bg)', padding: '12px 16px', borderRadius: '8px', border: '1px solid var(--border)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px' }}>
                    <span style={{ fontSize: '12px', fontWeight: 700, color: 'var(--text-primary)' }}>{t.stage}: {t.decision}</span>
                    <span style={{ fontSize: '10px', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>{new Date(t.timestamp).toLocaleDateString()}</span>
                  </div>
                  <p style={{ fontSize: '12px', color: 'var(--text-secondary)', fontStyle: 'italic', margin: 0 }}>"{t.reason}"</p>
                </div>
              ))}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
